### ISSUE TITLE
Is there a need for BytesToString and StringToBytes?

### ISSUE THREAD

**Issue by codyoss** [gramework/gramework#19]
Looking over the conv.go file I was confused by these two methods. Is there a reason they exist. You can convert from the two by just casting in Go, right?.

```go
package main

import (
	"fmt"
)

func main() {
	someBytes := []byte(">I am some bytes<")
	stringBytes := string(someBytes)
	fmt.Printf("%v, %T\n", stringBytes, stringBytes)
        // >I am some bytes<, string

	someString := ">I am a string<"
	bytesString := []byte(someString)
	fmt.Printf("%v, %T\n", bytesString, bytesString)
        // [62 73 32 97 109 32 97 32 115 116 114 105 110 103 60], []uint8
}
```

**Comment by kirillDanshin** [comment]
hey

just run `go test -bench=. -benchmem` and you should see the reason :)

**Comment by codyoss** [comment]
Holy Batman! Thank you for teaching me something new. Doing "magic" on readonly variables to convert them fast to save the copy, I like it!
