### ISSUE TITLE
Is gramework still using caddytls or tls of golang stdlib?

### ISSUE THREAD

**Issue by cih-y2k** [gramework/gramework#34]
I could not find the 3rd autoTLS implementation, placed in nettls_*.go, but found crypto/tls in AutoTLS implemetation. If gramework no longer used caddytls, Why?

**Comment by kirillDanshin** [comment]
AFAICT, we now using autocert+stdlib. I'll remove caddytls version later

**Comment by kirillDanshin** [comment]
if your question is answered and issue solved, I close the issue. if you have more things to ask feel free to reopen this issue or create a new one. good luck, thanks for using gramework :slightly_smiling_face:
