### ISSUE TITLE
*any with Index

### ISSUE THREAD

**Issue by rebootcode** [gramework/gramework#4]
Hi, while gramework supprts any route 

```
package main
import (
	"github.com/gramework/gramework"
)
func main() {
	app := gramework.New()
	app.GET("/*any", app.ServeDir("./files"))
	app.ListenAndServe()
}
```

It missed "/" as it was giving 403 error with message "directory view denied" , So, I created :- 

```
package main

import (
	"github.com/gramework/gramework"
)

func main() {
	app := gramework.New()
        app.ServeFile("/", "./files/index.html")    // As Index file
	app.GET("/*any", app.ServeDir("./files"))
	app.ListenAndServe()
}
```

But i get panic error of conflict between "/" and "/*any"

How can i add exception bar.

Thanks

**Comment by kirillDanshin** [comment]
Hi
Strange bug, I can't reproduce it. Can you send me ls -halF of your directory? Temrorary you can use ServeFilesCustom

**Comment by rebootcode** [comment]
HI @kirillDanshin , Yes i solved it with `ServeFilesCustom` . But the above error of conflict is as it is. I was surprised to see, why "index.html" was not taken as default file.

**Comment by kirillDanshin** [comment]
Ah, I see. It's default behaviour. I'll add check for index file and if it exists, we'll serve it. Otherwise, file list will be unavailable by default for security reasons. Will it resolve current issue?

**Comment by rebootcode** [comment]
Yes, that's expected output to fetch index.html or app folder name like for "template" folder -> template.html   just like in nodeJs. 

Thanks a lot :+1:

**Comment by kirillDanshin** [comment]
It will be calculated once on startup, so it will not compromise performance or speed. Working on patch.

Thanks for feedback :)

**Comment by kirillDanshin** [comment]
@rebootcode seems to be fixed in https://github.com/gramework/gramework/commit/d39a509328ca584ec655b1c3ff516644a4099d4c
please check it out and ping me on how it works for you and if it works for you at all. changing default name list seems to be enough for this case

**Comment by rebootcode** [comment]
Wow! That was easy! Will test today.

Thanks a lot for quick patch :)

**Comment by kirillDanshin** [comment]
thanks for feedback, glad to see you using Gramework.

please ping me when you test it or when you'll get more ideas or catch more bugs

**Comment by rebootcode** [comment]
Sure :+1: 

Thanks

**Comment by kirillDanshin** [comment]
@rebootcode hi again
is the patch works well for you?

**Comment by rebootcode** [comment]
@kirillDanshin Hi, I just tested it now and it works fine :) 

I was though checking with `serveFile` with `*any` route but specific file `index.html` as file path and it works fine with it too including all non-called `HTML` file. 

I feel this is `browser specific` behaviour with `ServeFile` as long as server is running and serving static assets , any HTML file called via `localhost` or via `file:` will be automatically parsed.

```
package main

import (
	"github.com/gramework/gramework"
)

func main() {
	app := gramework.New()
        app.ServeFile("/", "./files/index.html")
	app.ListenAndServe()
}
```

http://localhost will serve "index.html" by default and all other HTML files stored in directory with their page name like `http://localhost/page.html` 


This is amazing framework for sure.

**Comment by kirillDanshin** [comment]
Cool. If you want anything else ping me with a new issue. Thanks.

When gramework serving static assets, content type is detected by server. But when you open the file with a browser, content type is handled by browser. Now we're unable to include packagename.html support, cause it will cause difficult gramework support and may be unexpected for other users, like me. Also, check out SPAIndex() feature.

**Comment by kirillDanshin** [comment]
P.S. really glad to hear you like it :3
