### ISSUE TITLE
metrics middleware broken

### ISSUE THREAD

**Issue by dsvensson** [gramework/gramework#61]
I suspect it's bad to use gramework.BytesToString here:

https://github.com/gramework/gramework/blob/dev/metrics/metrics.go#L95

It causes errors like this in the /metrics endpoint:

```
* collected metric "gramework_http_requests_total" { label:<name:"code" value:"200" > label:
<name:"method" value:"POST" > label:<name:"node" value:"bb6f5bf92c76" > label:<name:"path" 
value:"/foo/Bars" > label:<name:"service" value:"/app" > label:<name:"type" value:"http" > counter:
<value:23 > } was collected before with the same name and label values
```

Looks like the underlying byte array mutates under gramework's feets. Swapping to string() fixes the issue.

Another symptom is that paths where some are longer than others, the shorter ones may get garbage at the end.

**Comment by kirillDanshin** [comment]
should be fixed in https://github.com/gramework/gramework/commit/f090fd454f08ebd468c8f6fbd0c1420daa085e4f

**Comment by kirillDanshin** [comment]
@dsvensson, please ping me if you have any further questions. for now, I'm closing this issue as fixed.
