### ISSUE TITLE
Failed to compiled in 1.13

### ISSUE THREAD

**Issue by waghanza** [gramework/gramework#68]
## Expected Behavior

I expect `gramework` to compile. The implementation is https://github.com/the-benchmarker/web-frameworks/blob/dependabot/docker/go/beego/golang-1.13.0/go/gramework/main.go

## Steps to Reproduce (for bugs)

1. go get of https://github.com/the-benchmarker/web-frameworks/blob/dependabot/docker/go/beego/golang-1.13.0/go/gramework/go.mod <- failing

## Your Environment

* Version used:
* Environment name and version (e.g. Go1.9 on CentOS 7, kernel 4.11.2): `Go 1.13`
* Server type and version: `Docker version 19.03.2, build 6a30dfc`
* Operating System and version: `Debian GNU/Linux 10`
* Link to your project: https://github.com/the-benchmarker/web-frameworks/blob/dependabot/docker/go/beego/golang-1.13.0/go/gramework/main.go

/cc @kirillDanshin

**Comment by kirillDanshin** [comment]
I fixed your build in https://github.com/the-benchmarker/web-frameworks/pull/1761 :) don't be afraid of `-rc*` in versions :)
