### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by sanqi** [gramework/gramework#9]
this working

`
func Test(ctx *fasthttp.RequestCtx) {
        ctx.SetContentType("text/html; charset=utf8")
	ctx.WriteString("testing")
}
`

it's not woring

`
func Test(ctx *gramework.Context) {
        ctx.SetContentType("text/html; charset=utf8")
	ctx.WriteString("testing")
}
`

**Comment by kirillDanshin** [comment]
thanks for reporting, checking out

**Comment by kirillDanshin** [comment]
@sanqi can't reproduce, sorry. please provide more info what exactly isn't working. I see that ContentType is sent correctly, response is also right.
Try `go get -u -v github.com/gramework/gramework` and `go get -u -v github.com/valyala/fasthttp` and check it again.
Also note, that gramework.Context.HTML() can replace setting this ContentType manually.

**Comment by sanqi** [comment]
Thank you. It seems that my local code is not pull complete

**Comment by sanqi** [comment]
hi @kirillDanshin 

finally, I found that other functions in the code were affected, and that's another question
I re wrote the bug example

`
import (
	"fmt"
	"github.com/gramework/gramework"
)

func main() {
	app := gramework.New()
	app.GET("/test/:id/", Test)
	app.ListenAndServe(":8000")
}

func Test(ctx *gramework.Context) {
	id := ctx.UserValue("id")
	fmt.Println("id > ", id)
	ctx.HTML()
	ctx.WriteString("testing")
}
`

`curl http://127.0.0.1:8000/test/1234/`
First use will output `id >  1234`
Request again can only get `id >  <nil>`

**Comment by kirillDanshin** [comment]
thanks for the code! working on the patch for you.

**Comment by kirillDanshin** [comment]
The bug occurrs when you use trailing slash in the path when registering handler.

thanks for reporting!

**Comment by kirillDanshin** [comment]
also, please ping me when you'll check if the patch resolves this issue completely

**Comment by sanqi** [comment]
This patch does solve this bug, but this patch brings another problem
Open http://127.0.0.1:8000/test/1234/ will be redirect to http://127.0.0.1:8000/test/1234
my previous project's URL paths are / have ended, and I'm using gramework refactoring.
Also, many web paths on the web are using / ending

**Comment by kirillDanshin** [comment]
I must note that redirection is done in a seo-safe way, so this temporary fix should be enough for a couple days. investigating if there are another ways to fix your issue.

**Comment by sanqi** [comment]
@kirillDanshin 

Thank you very much for your work 
If I don't use this patch, I can use *gramework.Context.Path() analyzes the processing of paths. To move on to the next step.
If using this patch, there seems to be no turning back

**Comment by kirillDanshin** [comment]
blocked by #14
